name: build-and-test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build-and-tests:
    strategy:
      matrix:
        - build: Debug
          sanitizer: address
        - build: Debug
          sanitizer: undefined-behaviour
        - build: Release
          sanitizer: undefined-behaviour
    runs-on: ubuntu-latest
    steps:
      - name: Get CMake
        uses: lukka/get-cmake@latest
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Install gcc
        uses: egor-tensin/setup-gcc@v1
      - name: Get conan
        uses: turtlebrowser/get-conan@main
      - name: Setup conan profile
        run: conan profile detect --force
      - name: Install dependecies
        run: conan install . -s build_type=${{matrix.BUILD_TYPE}} --output-folder=build --build=missing
      - name: Configure
        run: cmake -DCMAKE_BUILD_TYPE=${{matrix.BUILD_TYPE}} -DCMAKE_TOOLCHAIN_FILE=build/conan_toolchain.cmake -S. -B ./build
      - name: Compile
        run: cmake --build build -j
      - name: Test
        run: cd build/test && ctest --output-on-failure
